# Generated by Django 5.0.6 on 2024-05-11 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0003_auto_20240508_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_reference', models.CharField(max_length=100)),
                ('e_time', models.DateField(auto_now_add=True)),
                ('e_note', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('e_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authz.course')),
                ('e_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
